# Generated by Django 4.1.5 on 2023-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnounceMent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annos_name', models.CharField(max_length=80)),
                ('annosmt', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='potty')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=80)),
                ('notify', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PoojaTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pooja_name', models.CharField(max_length=250)),
                ('poojatime_from', models.TimeField()),
                ('poojatime_to', models.TimeField()),
            ],
        ),
    ]
