# Generated by Django 4.2 on 2023-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palaApp1', '0005_alter_enquiry_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='mobile_no',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='img',
            field=models.ImageField(blank=True, upload_to='Feeds'),
        ),
    ]
